stages:
  - prepare
  - build_and_test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    '&"C:\Program Files\Unity\Hub\Editor\2022.3.16f1\Editor\Unity.exe" -quit -batchmode -nographics -projectPath ./CENSIS-AR-App -executeMethod Builder.Build'
  tags:
    - unity
    
unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    '&"C:\Program Files\Unity\Hub\Editor\2022.3.16f1\Editor\Unity.exe" -batchmode -projectPath ./CENSIS-AR-App -runTests -testPlatform editmode -logFile -testResults ./unit-tests.xml | Out-Default'
  tags:
    - unity

image: $IMAGE:$UNITY_VERSION-base-$IMAGE_VERSION

get-unity-version:
  image: alpine
  stage: prepare
  variables:
    GIT_DEPTH: 1
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."