workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - lint
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    '&"C:\Program Files\Unity\Hub\Editor\2022.3.16f1\Editor\Unity.exe" -quit -batchmode -nographics -projectPath ./CENSIS-AR-App -executeMethod Builder.Build'
  tags:
    - unity
    
unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    '&"C:\Program Files\Unity\Hub\Editor\2022.3.16f1\Editor\Unity.exe" -batchmode -projectPath ./CENSIS-AR-App -runTests -testPlatform editmode -logFile -testResults ./unit-tests.xml | Out-Default'
  tags:
    - unity

mega-linter:
  stage: lint

  # You can override MegaLinter flavor used to have faster performances
  # More info at https://megalinter.io/latest/flavors/
  image: oxsecurity/megalinter-dotnet:v7

  # if script: ["true"] does not work, you may try this instead:
  #   script: [ "/bin/bash /entrypoint.sh" ]
  script: ["true"]

  variables:
    # All available variables are described in documentation
    # https://megalinter.io/latest/config-file/
    DEFAULT_WORKSPACE: $CI_PROJECT_DIR

    # ADD YOUR CUSTOM ENV VARIABLES HERE TO OVERRIDE VALUES OF .mega-linter.yml
    # AT THE ROOT OF YOUR REPOSITORY
  tags:
   - docker

  artifacts:
    when: always
    paths:
      - report
    expire_in: 1 week

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."